[package]
name = "multitouch_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.88.8"
project-root = "0.2.2"
tuio-rs = "0.2.0"
